services:

  db:
    image: cgr.dev/chainguard/postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  fastapi:
    build: .
    command: poetry run uvicorn arquivos_py.main:app --reload --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      - ENV=development
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}
    networks:
      - app-network
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: {}

