name: Pipeline
on: 
  push:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - 
        name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
      
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            keilalinhares/studentregistryapi:v1.0.0
